### ISSUE TITLE
bad_alloc error

### ISSUE THREAD

**Issue by NuageLee** [weigao95/surfelwarp#11]
Hi,
Last time I encountered an error, I found that it was about GPU memory. So I changed a GPU to TitanXP and solve it, but this time I got a "std::bad_alloc", was it because I didn't have enough memory? (32G)

![image](https://user-images.githubusercontent.com/36405884/65735552-7035b000-e10a-11e9-8265-51bf83ee23cb.png)

**Comment by weigao95** [comment]
Can you trace the call stack for this exception (maybe using a debugger)? It's hard to tell which code throws this error.
