### ISSUE TITLE
Some cilantro files have moved

### ISSUE THREAD

**Issue by timhutton** [weigao95/surfelwarp#28]
e.g. the SurfelWarp code refers to `#include <cilantro/point_cloud.hpp>` which doesn't exist - is now `cilantro/utilities/point_cloud.hpp`

**Comment by bsespede** [comment]
Hi Tim, I've used this commit from cilantro and it worked perfectly: `e9eb9f3c5c75710eb6cfeeb6313b5a73aaa06a28`

**Comment by timhutton** [comment]
Great, thanks. That commit could usefully go in the documentation.

**Comment by weigao95** [comment]
Sorry for my delayed reply as I'm struggling with the RSS deadline these days and I'm glad to see you solve the problem. I will a note to documentation.

**Comment by henry123-boy** [comment]
Hi! thank you for your great work and codes. Unfortunately, I met the same problem three years latter after this issues been closed, but it seems does not work using the `e9eb9f3c5c75710eb6cfeeb6313b5a73aaa06a28` version of cilanto.
