### ISSUE TITLE
The pre-allocated buffer is not enough.

### ISSUE THREAD

**Issue by NuageLee** [weigao95/surfelwarp#3]
Hi,
I run it on Ubuntu16.04 with GTX 980ti, it says "The pre-allocated buffer is not enough" and give me a runtime_error.
buffer size = 50000 and size = 72748. 

Any help will be much appreciated.

**Comment by weigao95** [comment]
You might modify the constants in ${project_root}/common/Constants.cpp

50000 seems to be "Constants::kMaxNumSurfelCandidates", you can change it to a larger number like 100000.

**Comment by ZYJxxx** [comment]
> Hi,
> I run it on Ubuntu16.04 with GTX 980ti, it says "The pre-allocated buffer is not enough" and give me a runtime_error.
> buffer size = 50000 and size = 72748.
> 
> Any help will be much appreciated.

hi,
have you solved this problem, and how did you do that? hope for your reply.
