### ISSUE TITLE
error: identifier "Matrix3f" is undefined

### ISSUE THREAD

**Issue by liyiming001** [weigao95/surfelwarp#31]
Dear author:
       I have success to cmake the file by following the second installation guide.However something error occurred.as the following:
      /surfelwarp/common/common_types.h(26): error: identifier "Matrix3f" is undefined
      /surfelwarp/common/common_types.h(26): error: expected a ";"
     ...
    and I guess that the version of eigen or boost is incompatible with project.try some version but still error.I don't know how to solve this problem.So can you give me some advice if possible.Thanks.

**Comment by weigao95** [comment]
Can you pose the log from cmake?

**Comment by liyiming001** [comment]
As following

**Comment by liyiming001** [comment]
/home/lym/图片/1.png
/home/lym/图片/2.png
/home/lym/图片/3.png

**Comment by liyiming001** [comment]
just like this

**Comment by liyiming001** [comment]
just like this

**Comment by liyiming001** [comment]
![1](https://user-images.githubusercontent.com/55123507/76136351-780b6000-606b-11ea-935d-2171dff1928b.png)
![2](https://user-images.githubusercontent.com/55123507/76136356-85284f00-606b-11ea-8004-f14a1ab9202e.png)
![3](https://user-images.githubusercontent.com/55123507/76136402-01229700-606c-11ea-84f9-f4b8758180ce.png)
just like this

**Comment by weigao95** [comment]
It seems the problem comes from using Eigen with CUDA. Can you try a simpler program that includes Eigen header in .cu file and make sure it works? You might need to inspect cmake cache to ensure you are testing the Eigen that produces the error you mentioned.

**Comment by liyiming001** [comment]
It required Eigen3.3.9 according to your documents when install cilantro.however the latest version is 3.3.7。In the CmakeList.txt:
# Do not use the system Eigen
set(EIGEN_ROOT "${CMAKE_SOURCE_DIR}/external/eigen3.4")
set(EIGEN_INCLUDE_DIR ${EIGEN_ROOT})

I think maybe this is season why I failed. So what is the true version in your task.

**Comment by Cartucho** [comment]
I had the same issue and I fixed it by uncommenting the following line: https://github.com/weigao95/surfelwarp/blob/6e547e6b33b49d903475b869a58c9bda7b9c3061/CMakeLists.txt#L70
