### ISSUE TITLE
[Question] Does surfelwarp assume that the camera always stay still?

### ISSUE THREAD

**Issue by xiaotaw** [weigao95/surfelwarp#33]
In VolumnForm dataset, the camera barely move. And I haven't found any code about coordinate transformation between camera and world.

Does surfelwarp assume that the camera always stay still, and not turn around?

**Comment by weigao95** [comment]
No. There is a rigid pre-solve before the non-rigid registration.

**Comment by xiaotaw** [comment]
I fetched color and depth image from a kinect dk camera (by rewriting some functions: FetchXxxxxImage). And start surfelwarp app to reconstruct a static scene(a dinner table). I held the camera, walking around the table, and the reconstruction failed.

**Comment by weigao95** [comment]
The patch collider is not trained for that scene I think.

**Comment by xiaotaw** [comment]
What can I do to finetune gpc model for custom scene?
