### ISSUE TITLE
I hope to get some advice

### ISSUE THREAD

**Issue by shugao1** [weigao95/surfelwarp#36]
Hello author, I want to implement your project with VS2019 on win10. Based on VCPKG, I installed libraries PCL, GLFW3, eigen, pangolin, and added cliantro to the subdirectory, but encountered many problems, I hope to get some guidance from you.

**Comment by weigao95** [comment]
I used to develop the code on win10, but I do not have a vs2019 environment and cannot test it myself.

Can you be more specific about the problem you encountered?
