### ISSUE TITLE
Get rid of PCL dependency

### ISSUE THREAD

**Issue by Algomorph** [weigao95/surfelwarp#4]
This is, in a sense, a feature request, or, to be more exact, an enhancement request.

PCL's versions are not very backward-compatible, and building just the right PCL with just the right feature support means messing with the dependency hell so very inherent to PCL.

To give some idea, just to deal with the old PCL version + support for only the older version of CUDA already took me over six hours to resolve, and I'm not done yet.

My recommendation is to keep this issue open even if the maintainers decide they don't want to address this right now. Maybe, someone will come up with a PR, IDK.

**Comment by weigao95** [comment]
Yeah, the code is developed when CUDA 9 is the latest. PCL is used mainly for debug visualization and it might worth to keep it only in `${project_root}/visualization` and mark as optional.

I will take a look after the ICRA deadline and you are very welcomed to come up with a PR if you want.

**Comment by weigao95** [comment]
Thanks for your work, that's great! I will test it on my machine.
