### ISSUE TITLE
Failed to Solve on Boxing-like dataset

### ISSUE THREAD

**Issue by xiaotaw** [weigao95/surfelwarp#43]
Hello, I was trying to repeat `Boxing` using a live camera. It failed to seperate fist from face.
cliped_filter_depth:
![cliped_filter_depth](https://user-images.githubusercontent.com/13536925/81638392-a29ede00-944b-11ea-9ada-4978a7314319.png)
reference_phong:
![reference_phong](https://user-images.githubusercontent.com/13536925/81638409-b0546380-944b-11ea-82be-8be7186c7495.png)
live_phone:
![live_phong](https://user-images.githubusercontent.com/13536925/81638420-b8140800-944b-11ea-8195-cb2be9f622a1.png)

**Comment by weigao95** [comment]
You might try to modify the re-init parameter.

**Comment by 411066282** [comment]
@xiaotaw how did you do this, with live camera? just modify the fetch image interface?
