### ISSUE TITLE
How to improve the efficiency of reconstruction

### ISSUE THREAD

**Issue by shugao1** [weigao95/surfelwarp#44]
Hello! I implemented your program in Ubuntu, running a data set, but I need 3s to process a frame of image, it looks like your video is more efficient to rebuild, what's the reason?

**Comment by weigao95** [comment]
It shouldn't be that slow. Please check 1) have you turned out offline rendering 2) have you built with release.

You may check: https://github.com/weigao95/surfelwarp/issues/39 for more discussion.
