### ISSUE TITLE
CUDA_cublas_LIBRARY not found

### ISSUE THREAD

**Issue by Dhruva-Storz** [weigao95/surfelwarp#45]
Hi, 

Ive got an issue with building. All the steps in the build instructions worked fine up until the build stage, where I get the following error 

```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
 Please set them or make sure they are set and tested correctly in the CMake files:
 CUDA_cublas_LIBRARY (ADVANCED)
     linked by target "solver_lib" in directory /homes/dg1119/IP/surfelwarp/pcg_solver
     linked by target "core_lib" in directory /homes/dg1119/IP/surfelwarp/core
```

I am using `Cuda 10.1 on ubuntu 18.04`

I also got a similar error with CUDA_cublas_device_LIBRARY, but this was solved by using a newer version of Cmake as per issue #22, however this one remained. 

Thanks

**Comment by HerB1998** [comment]
> Hi,
> 
> Ive got an issue with building. All the steps in the build instructions worked fine up until the build stage, where I get the following error
> 
> ```
> CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
>  Please set them or make sure they are set and tested correctly in the CMake files:
>  CUDA_cublas_LIBRARY (ADVANCED)
>      linked by target "solver_lib" in directory /homes/dg1119/IP/surfelwarp/pcg_solver
>      linked by target "core_lib" in directory /homes/dg1119/IP/surfelwarp/core
> ```
> 
> I am using `Cuda 10.1 on ubuntu 18.04`
> 
> I also got a similar error with CUDA_cublas_device_LIBRARY, but this was solved by using a newer version of Cmake as per issue #22, however this one remained.
> 
> Thanks

hello, I got the same problem,would you tell me how to fix it?
