### ISSUE TITLE
The apply of FilterReg in 3D reconstruct

### ISSUE THREAD

**Issue by Sunzhiliang** [weigao95/surfelwarp#48]
Recently ，I am interesting in your work "FilterReg:Robust and Efficient Probabilistic Point-Set Registration，CVPR 2019", I try to find it here,but failed. Where is the  the apply of FilterReg in 3D reconstruct?

**Comment by weigao95** [comment]
It is in another repo of that paper. The integration is pretty dirty thus not released. I may spend some time on that later and you are welcomed to try it if you want.
