### ISSUE TITLE
how to visualize the program output while running?

### ISSUE THREAD

**Issue by ByLee1997** [weigao95/surfelwarp#50]
I've run the surfelwarp_app and it execute normally and produce png output in the folder, but I can't see the output when running.

When I change the **_glfwWindowHint(GLFW_VISIBLE, GL_TRUE)_** in **_surfelwarp::Renderer::initGLFW()_**, it create a window and has an error of no response.

My environment is ubuntu16.04 RTX2070 cuda10.0, using cilantro

**Comment by weigao95** [comment]
See: https://github.com/weigao95/surfelwarp/issues/37#issue-606914871

**Comment by 411066282** [comment]
@ByLee1997 Have you solved this? After seeing "#37 (comment)"
