### ISSUE TITLE
Error: Nan in node candidate 

### ISSUE THREAD

**Issue by jmg1002** [weigao95/surfelwarp#51]
I've run the surfelwarp_app and it printed error ${project_root}/core/geometry/WarpFieldUpdater.cpp:24: Nan in code candidate

Actually, in the case of The 0th Frame, the code was executed and the above error message was outputted in the 1th Frame.

I thick this is a CUDA setting problem. I want to know how to fix this error...

My environment is ubuntu 16.04, GTX TITAN X cuda9.0 using PCL.

**Comment by weigao95** [comment]
I don't think that's likely not a cuda setting problem. Can you visualize the first frame to ensure the points are OK?
