### ISSUE TITLE
How to acquire deformation vector field of 2 point clouds?

### ISSUE THREAD

**Issue by qaler** [weigao95/surfelwarp#54]
Hello @weigao95, many thanks to your contributions of maintaining this promising and fast reconstruction library!

I want to know if there is any way to apply deformation registration to 2 point clouds and acquire the deformation vector field by using your library? I guess the registration result of 2 depth frames is stored inside [SurfelWarpSerial.cpp](https://github.com/weigao95/surfelwarp/blob/master/core/SurfelWarpSerial.cpp) code, but I don't know how to get the vector field from it.

Thanks for your help!

**Comment by Wangyouai** [comment]
Hello, are you using ubuntu and cuda10.0?

**Comment by weigao95** [comment]
The registration code is tightly integrated with other parts, like image and geometry processing. I think it is not easy to separate that out. But you might convert your two point-clouds into two depth images and try to run the algorithm on it.
