### ISSUE TITLE
incompatible for higher-level cuda & gpu

### ISSUE THREAD

**Issue by Cryst4L9527** [weigao95/surfelwarp#56]
when I try to run this code on nividia RTX3090 with cuda11.1,there is a new problem as below: 
'shfl' without '.sync' is not supported on .target sm_70 and higher from PTX ISA version 6.4 
It seems that the cuda code is not suitable for the novel gpu for some reason.Would you update your code to fit the new feature?I'll appreciate it very much!

**Comment by BaldrLector** [comment]
Hi, you need to change the CMakeLitsts.txt, refer to #23

**Comment by Cryst4L9527** [comment]
I've changed the CMakeLists.txt，it seems that the problem is the cuda10+ doesn't support the shfl without sync anymore.

**Comment by weigao95** [comment]
I remember that shfl will be deprecated. You need to change the device instrinsics. In the `common/device_instrinsics.h` file, you need to change `shfl.up.b32` into `shfl.sync.up.b32 ` according to this doc: https://docs.nvidia.com/cuda/parallel-thread-execution/index.html. You need to add `sync` for all data types.

**Comment by Cryst4L9527** [comment]
Thank you very much！In fact I change the arch to sm_61 when compile and it worked too，but maybe this operation will affect the speed.I'll try to change them.



At 2021-02-04 11:53:17, "Wei Gao" <notifications@github.com> wrote:

I remember that shfl will be deprecated. You need to change the device instrinsics. In the common/device_instrinsics.h file, you need to change shfl.up.b32 into shfl.sync.up.b32 according to this doc: https://docs.nvidia.com/cuda/parallel-thread-execution/index.html. You need to add sync for all data types.
