### ISSUE TITLE
how to run this demo with my own data?

### ISSUE THREAD

**Issue by bianlongpeng** [weigao95/surfelwarp#59]
A very nice work !, but I don't down how to run this demo with my own data. When I click the link in the pic,  
![image](https://user-images.githubusercontent.com/22487109/106566637-8740a980-656b-11eb-9885-923ae5ee03f1.png)it report 404 error. At the same time, I want to know how to convert my data into the format of VolumeDeform. Is there an example for reference?

**Comment by weigao95** [comment]
I guess just write a simple python script? There is nothing more than a little bit of file management.
