### ISSUE TITLE
About gaussian newton iteration.

### ISSUE THREAD

**Issue by xiayeqingfeng** [weigao95/surfelwarp#60]
Hi@weigao95, 

I notice that there are two iteration methods in gaussian newton loop: ***solverIterationGlobalIterationStreamed*** and ***solverIterationLocalIterationStreamed***, it seems that you run the global iteration 3 times and the local iteration 3 times each. In the global iteration, the density and foreground term is disabled and in the local iteration the density term is enabled. I can't quickly figure out the intuition of this design and here are my two questions:

1. What's the consideration behind such design that to spilt the gaussian newton loop to global and local interations like this ?
2. The codes in ***solverIterationGlobalIterationStreamed*** and ***solverIterationLocalIterationStreamed*** seems identical? Can we just use one function instead of two?

Thanks in advance! Any discussion is welcome!

**Comment by weigao95** [comment]
1. The image density term has a very small convergence range
2. Yes, almost identical. Just whether the image density term is invoked or not.
