### ISSUE TITLE
how to run this demo with a RGBD camera?

### ISSUE THREAD

**Issue by bianlongpeng** [weigao95/surfelwarp#63]
A very nice work. Now I have successfully run this demo, but how to run the demo with a RGBDcamera and how can I configure it?

**Comment by weigao95** [comment]
That depends on your camera driver. Override the fetch interface built upon your camera driver and use it with the main pipeline.

**Comment by 411066282** [comment]
@ bianlongpeng have you solved your problem?

**Comment by 411066282** [comment]
@bianlongpeng  have you solved your problem?

**Comment by electro-logic** [comment]
@bianlongpeng @411066282 have a look at https://github.com/electro-logic/surfelwarp-modern/tree/feature/realsense
